#!/usr/bin/env bash

if [ $# == 0 ]; then
    exit 3
fi

CUR_DIR=$(pwd)
APP_DIR="$CUR_DIR"
PRJ_NAME="${!#}"
SUFFIX="ctl"
__bcl_path=$( ls -alh "$HOME"/.local/bin/bcl )

if [[ ! -d "$CUR_DIR/$PRJ_NAME" ]]; then
    echo "Project $PRJ_NAME is not found."
    exit 1
fi

if [[ ! -d "$CUR_DIR/$PRJ_NAME/blueprint" ]]; then
    mkdir -p "$CUR_DIR/$PRJ_NAME/blueprint"
fi

if [[ ! -d "$CUR_DIR/$PRJ_NAME/files" ]]; then
    mkdir -p "$CUR_DIR/$PRJ_NAME/files"
fi

if [[ ! -d "$CUR_DIR/$PRJ_NAME/framework" ]]; then
    mkdir -p "$CUR_DIR/$PRJ_NAME/framework"
fi

if [[ ! -d "$CUR_DIR/$PRJ_NAME/playbook" ]]; then
    mkdir -p "$CUR_DIR/$PRJ_NAME/playbook"
fi

__bcl_framework_path=$( echo "$__bcl_path" | awk '{print $11}' | sed 's/\/cli/\/framework\//g')
cp "$__bcl_framework_path"* "$CUR_DIR/$PRJ_NAME/framework"

sed -i.bak "s/function_name/_bash_cli_$PRJ_NAME$SUFFIX/g" "$CUR_DIR/$PRJ_NAME/framework/complete"
rm "$CUR_DIR/$PRJ_NAME/framework/complete.bak"

sed -i.bak "s/__project_name__/$PRJ_NAME/g" "$CUR_DIR/$PRJ_NAME/framework/complete"
rm "$CUR_DIR/$PRJ_NAME/framework/complete.bak"

sed -i.bak "s/__project_name__/$PRJ_NAME/g" "$CUR_DIR/$PRJ_NAME/framework/help"
rm "$CUR_DIR/$PRJ_NAME/framework/help.bak"

sed -i.bak "s/__project_name__/$PRJ_NAME/g" "$CUR_DIR/$PRJ_NAME/framework/cli"
rm "$CUR_DIR/$PRJ_NAME/framework/cli.bak"

if [[ -d "$CUR_DIR/$PRJ_NAME/app" ]]; then
    APP_DIR="$APP_DIR/$PRJ_NAME/app"
else
    mkdir -p "$APP_DIR/$PRJ_NAME/app"
    APP_DIR="$APP_DIR/$PRJ_NAME/app"
fi

if [[ ! -d "$APP_DIR/autocomplete" ]]; then
    mkdir -p "$APP_DIR/autocomplete"
fi

__bcl_autocomplete_path=$( echo "$__bcl_path" | awk '{print $11}' | sed 's/\/cli/\/autocomplete\//g')
cp "$__bcl_autocomplete_path"* "$APP_DIR/autocomplete"

sed -i.bak "s/__project_name__/$PRJ_NAME/g" "$APP_DIR/autocomplete/apply"
rm "$APP_DIR/autocomplete/apply.bak"

sed -i.bak "s/__project_name__/$PRJ_NAME/g" "$APP_DIR/autocomplete/remove"
rm "$APP_DIR/autocomplete/remove.bak"

# Render the *ctl entrypoint
mv "$CUR_DIR/$PRJ_NAME/framework/entrypoint" "$CUR_DIR/$PRJ_NAME$SUFFIX"
sed -i.bak "s/__project_name__/$PRJ_NAME/g" "$CUR_DIR/$PRJ_NAME$SUFFIX"
rm "$CUR_DIR/$PRJ_NAME$SUFFIX.bak"

chmod +x "$CUR_DIR/$PRJ_NAME$SUFFIX"

>&2 echo "Updated BCL build on project: $PRJ_NAME."
