#!/usr/bin/env bash
echo -e "\033[36mUpgrading BCL framework\033[39m"
BCL_INSTALLATION_DIR=$(dirname "$(dirname "$(dirname "${BASH_SOURCE[0]}")")")

pushd "$BCL_INSTALLATION_DIR" || exit
git reset --hard HEAD
git pull https://github.com/BrunIF/bcl.git master
popd || exit

echo -e "\033[36mBCL framework is upgraded to latest\033[39m"