#!/usr/bin/env bash

# shellcheck disable=SC1090
source "$ROOT_DIR"/app/.helper/system

APP_DIR=$(pwd)
NAME=bcl

INSTALLATION_DIR="$HOME/.local/bin"
BASH_COMPLETION_FILE="$HOME/.bash_completion"
BASH_COMPLETION_DIR="$HOME/.bash_completion.d"
USER=$(echo "$HOME" | sed -e 's/\/.*\///g')
GROUP=$(groups | awk '{print $1}')

if [[ -f "$APP_DIR/.bash_cli" ]]; then
    APP_DIR=$(dirname "$APP_DIR")
fi

if [[ ! -f "$APP_DIR/app/.bash_cli" ]]; then
    >&2 echo -e "\033[31mYou are not within a Bash CLI project\033[39m"
    >&2 echo "Please change your directory to a valid project or run the init command to set one up."
    exit 1
fi

if [[ ! -d "$INSTALLATION_DIR" ]]; then
    mkdir -p "$INSTALLATION_DIR"
fi

if [[ ! -d "$BASH_COMPLETION_DIR" ]]; then
    mkdir -p "$BASH_COMPLETION_DIR"
fi

if [[ ! -f "$INSTALLATION_DIR/$NAME" ]]; then
    ln -s "$APP_DIR/cli" "$INSTALLATION_DIR/$NAME"
fi

cat > "$BASH_COMPLETION_DIR/$NAME" <<EOC
source "$APP_DIR/complete"
complete -F _bash_cli $NAME
EOC

[[ $EUID -ne 0 ]] && chown -R "$USER":"$GROUP" "$BASH_COMPLETION_DIR"

if [[ ! -f "$BASH_COMPLETION_FILE" ]]; then
    cat > "$BASH_COMPLETION_FILE" <<EOC
for BCFILE in ~/.bash_completion.d/* ; do
source \$BCFILE
done
EOC
  [[ $EUID -ne 0 ]] && chown "$USER":"$GROUP" "$BASH_COMPLETION_FILE"
fi

echo "BCL installed to $INSTALLATION_DIR/$NAME"

if [ "$(kernel)" == "Darwin" ] && [ ! -f /usr/local/etc/bash_completion ]; then
    echo ""

    echo "bash-completion is not installed. Autocomplete will not work" \
        "correctly. You can install bash-completion with:" | fold -sw80
    echo "  $ brew install bash-completion"
    echo "  $ echo \"[ -f /usr/local/etc/bash_completion ] && . /usr/local/etc/bash_completion\" >> ~/.bash_profile"
    echo "  $ source ~/.bash_profile"
fi

if ! echo "$PATH" | _grep -e "$INSTALLATION_DIR" > /dev/null 2>&1; then
    echo ""

    echo "Please add '$INSTALLATION_DIR' into your \$PATH variable" \
            "(without the quote). You can do this by adding this line to" \
            "your ~/.bashrc or ~/.zshrc file:" | fold -sw80

    echo "export PATH=$INSTALLATION_DIR:\$PATH" >> ~/.bashrc && \
        echo "We add  " "export PATH=\"$INSTALLATION_DIR:\$PATH\"" " to your ~/.bashrc"
fi
