#!/usr/bin/env bash

set -e

# kernel returns the kernel type of the system
function kernel() {
    uname -s
}

# platform returns architecture string that identifies the kernel AND machine
# bit length of this system. The returned string is in the format of
# <kernel>-<arch> in lowercase, e.g.:
#   - Normal Linux and Chromebook:  linux-x86_64
#   - Mac OS:                       darwin-x86_64
function platform() {
    kern="$(kernel | tr '[:upper:]' '[:lower:]')"
    local kern
    arch="$(uname -m | tr '[:upper:]' '[:lower:]')"
    local arch

    echo "${kern}-${arch}"
}

# _readlink wraps readlink in Linux or greadlink in Mac OS
function _readlink() {
    if [ "$(kernel)" == "Linux" ]; then
        readlink "$@"
        return $?
    elif [ "$(kernel)" == "Darwin" ]; then
        greadlink "$@"
        return $?
    fi

    echo "readlink: invalid kernel name $(kernel)" >&2
    return 1
}

# _grep wraps grep in Linux or ggrep in Mac OS
function _grep() {
    if [ "$(kernel)" == "Linux" ]; then
        grep "$@"
        return $?
    elif [ "$(kernel)" == "Darwin" ]; then
        ggrep "$@"
        return $?
    fi

    echo "grep: invalid kernel name $(kernel)" >&2
    return 1
}
